Add job to OpenCI workflow that creates classes

diff --git a/.github/workflows/openapi.yml b/.github/workflows/openapi.yml
--- a/.github/workflows/openapi.yml
+++ b/.github/workflows/openapi.yml
@@ -47,13 +47,15 @@ jobs:
           pip install -r requirements/test.txt
           pip install -r requirements/types.txt
           pip install -r requirements/scripts.txt
+
       - name: Fetching OpenAPI spec
         run: |
           # Fetching OpenAPI spec
           python scripts/openapi.py fetch api.github.com 2022-11-28 api.github.com.2022-11-28.json
-      - name: Sync with OpenAPI spec
+
+      - name: Sync with OpenAPI spec (ignore unimplemented schemas)
         run: |
-          # Sync with OpenAPI spec
+          # Sync with OpenAPI spec (ignore unimplemented schemas)
           git checkout -b openapi/main
           ./scripts/openapi-update-classes.sh --branch-prefix openapi/autosync 2> openapi-update-classes.log
       - name: Changes
@@ -73,7 +75,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: Logs
+          name: Sync logs
           path: |
             *.log
       - name: Commit changes
@@ -97,5 +99,54 @@ jobs:
           # Fail on changes
           if ! git diff --quiet openapi/main; then
             echo "Changes exist, please investigate branch openapi/autosync"
+            exit 1
+          fi
+
+      - name: Sync with OpenAPI spec (create new classes)
+        run: |
+          # Sync with OpenAPI spec (create new classes)
+          git checkout openapi/autosync
+          ./scripts/openapi-update-classes.sh --create-classes --branch-prefix openapi/autosync-new-classes 2> openapi-update-classes.log
+      - name: Changes
+        run: |
+          # Show changes
+          git branch -a | grep openapi/autosync-new-classes- | grep -v -E -e "-[0-9]+$" | while read branch; do
+            echo "::group::$branch"
+            git log --oneline "$branch...openapi/main"
+            git diff openapi/main "$branch"
+            echo "::endgroup::"
+          done
+      - name: Log on error
+        if: failure()
+        run: |
+          cat openapi-update-classes.log
+      - name: Upload logs
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: Create new classes logs
+          path: |
+            *.log
+      - name: Commit changes
+        run: |
+          # Commit changes
+          git checkout -b openapi/autosync-new-classes
+          git branch -a | grep openapi/autosync-new-classes- | grep -v -E -e "-[0-9]+$" | while read branch; do
+            echo "::group::$branch"
+            git merge --squash "$branch"
+            git commit --no-edit
+            echo "::endgroup::"
+          done
+
+          # push if there are changes
+          if ! git diff --quiet openapi/main; then
+            echo "Pushing changes to origin openapi/autosync-new-classes"
+            git push origin openapi/autosync-new-classes
+          fi
+      - name: Fail on changes
+        run: |
+          # Fail on changes
+          if ! git diff --quiet openapi/main; then
+            echo "Changes exist, please investigate branch openapi/autosync-new-classes"
             exit 1
           fi
